<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class NewUserAccountCreatedNotification extends Notification
{
    use Queueable;

    public function __construct(
        public string $plainPassword,
        public string $assignedRole,
        public bool $isAutoGenerated,
    ) {
    }

    /**
     * Get the notification's delivery channels.
     *
     * @return array<int, string>
     */
    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    /**
     * Get the mail representation of the notification.
     */
    public function toMail(object $notifiable): MailMessage
    {
        $role = strtolower((string) $this->assignedRole);
        $roleLabel = ucfirst($role);
        $appName = 'Cypherox Memories';

        $roleSummary = match ($role) {
            'admin' => 'You can manage users, albums, and platform-wide settings.',
            'manager' => 'You can manage albums, upload media, and coordinate team content.',
            default => 'You can access and contribute to assigned albums and media.',
        };

        return (new MailMessage())
            ->subject("Welcome to {$appName} - Your account is ready")
            ->view('emails.users.account-created', [
                'appName' => $appName,
                'name' => $notifiable->name,
                'email' => $notifiable->email,
                'password' => $this->plainPassword,
                'roleLabel' => $roleLabel,
                'roleSummary' => $roleSummary,
                'isAutoGenerated' => $this->isAutoGenerated,
                'logoUrl' => asset('images/cx-logo-dark.svg'),
                'loginUrl' => route('login'),
            ]);
    }

    /**
     * Get the array representation of the notification.
     *
     * @return array<string, mixed>
     */
    public function toArray(object $notifiable): array
    {
        return [];
    }
}
